In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Ram", "Shyam", "Hari", "Sita", "Gita"],
    "Age": [20, np.nan, 22, None, 21],
    "Math": [80, 75, np.nan, 90, None],
    "Science": [85, np.nan, 78, 92, 88],
    "City":["Kathmandu","Pokhara","Lalitpur",None,"Lalitpur"]
})

print(df)

    Name   Age  Math  Science       City
0    Ram  20.0  80.0     85.0  Kathmandu
1  Shyam   NaN  75.0      NaN    Pokhara
2   Hari  22.0   NaN     78.0   Lalitpur
3   Sita   NaN  90.0     92.0        NaN
4   Gita  21.0   NaN     88.0   Lalitpur

In [7]:
#removing rows containing null
# df.dropna(axis,inplace=True) #it will remove rows from original array
#axios=0 means row
#axios=1 means column
#dropna remove the row or column which have null value
df.dropna(axis=1) #it will drop column

    Name
0    Ram
1  Shyam
2   Hari
3   Sita
4   Gita

In [ ]:
#thresh parameter
df.dropna(axis=1,thresh=4)
#remove those column 
# which has less than 
# 4 non null data

    Name  Science       City
0    Ram     85.0  Kathmandu
1  Shyam      NaN    Pokhara
2   Hari     78.0   Lalitpur
3   Sita     92.0        NaN
4   Gita     88.0   Lalitpur

In [5]:
df.dropna(axis=0) #it will remove rows

  Name   Age  Math  Science       City
0  Ram  20.0  80.0     85.0  Kathmandu

In [ ]:
df.dropna(axis=0,thresh=4)

   Name   Age  Math  Science       City
0   Ram  20.0  80.0     85.0  Kathmandu
2  Hari  22.0   NaN     78.0   Lalitpur
4  Gita  21.0   NaN     88.0   Lalitpur

In [ ]:
df.dropna(axis=0,thresh=100) 
#it does not show row as non of the row has at least 100 non null data

Empty DataFrame
Columns: [Name, Age, Math, Science, City]
Index: []