In [85]:
#we generall fill column rather than row
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Ram", "Shyam", "Hari", "Sita", "Gita"],
    "Age": [20, np.nan, 22, None, 21],
    "Math": [80, 75, np.nan, 90, None],
    "Science": [85, np.nan, 78, 92, 88],
    "City":["Kathmandu","Pokhara","Lalitpur",None,"Lalitpur"]
})

print(df)

    Name   Age  Math  Science       City
0    Ram  20.0  80.0     85.0  Kathmandu
1  Shyam   NaN  75.0      NaN    Pokhara
2   Hari  22.0   NaN     78.0   Lalitpur
3   Sita   NaN  90.0     92.0        NaN
4   Gita  21.0   NaN     88.0   Lalitpur

In [90]:
# df.fillna(value)#it fill all non value with value
df.fillna(0)

    Name   Age  Math  Science       City
0    Ram  20.0  80.0     85.0  Kathmandu
1  Shyam   0.0  75.0      0.0    Pokhara
2   Hari  22.0   0.0     78.0   Lalitpur
3   Sita   0.0  90.0     92.0          0
4   Gita  21.0   0.0     88.0   Lalitpur

In [96]:
# df.fillna({"Math":0,"Science":0},inplace=True) #inplace change orginal data
df.fillna({"Math":0,"Science":0})
#it fill Math nan value with 0 and Science nan value with 0 other remains unchanged

    Name   Age  Math  Science       City
0    Ram  20.0  80.0     85.0  Kathmandu
1  Shyam   NaN  75.0      0.0    Pokhara
2   Hari  22.0   0.0     78.0   Lalitpur
3   Sita   NaN  90.0     92.0        NaN
4   Gita  21.0   0.0     88.0   Lalitpur

In [97]:
df.fillna({
    "Math":df["Math"].mean(),
    "Science":df["Science"].mean(),
    "City":df["City"].mode()[0]
     

    },)

    Name   Age  Math  Science       City
0    Ram  20.0  80.0     85.0  Kathmandu
1  Shyam   NaN  75.0      0.0    Pokhara
2   Hari  22.0   0.0     78.0   Lalitpur
3   Sita   NaN  90.0     92.0   Lalitpur
4   Gita  21.0   0.0     88.0   Lalitpur

df.fillna({"Math":df["Math].mean(),"Science":df["Science].mean()})