In [6]:
#it does not need any inbuilt library
#Categorical data
    #nominal (no mathmetical value,no order)
        #use oneHotEncoder  for input variable
        #use labelEncoder for output variable
    #ordinal (has mathmetical value,order)
        #use  ordinalEncoder for input variable
        #use ordinalEncoder for output variable

import pandas as pd

df = pd.DataFrame({
    "Study Hours": [2, 3, 4, 5, 6, 7, 1, 8],
    "Attendance": [60, 65, 70, 75, 80, 85, 50, 90],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Result": ["Fail", "Fail", "Pass", "Pass", "Pass", "Pass", "Fail", "Pass"]
})

print(df)

   Study Hours  Attendance  Gender Result
0            2          60    Male   Fail
1            3          65  Female   Fail
2            4          70    Male   Pass
3            5          75  Female   Pass
4            6          80    Male   Pass
5            7          85  Female   Pass
6            1          50    Male   Fail
7            8          90  Female   Pass

In [7]:
df

   Study Hours  Attendance  Gender Result
0            2          60    Male   Fail
1            3          65  Female   Fail
2            4          70    Male   Pass
3            5          75  Female   Pass
4            6          80    Male   Pass
5            7          85  Female   Pass
6            1          50    Male   Fail
7            8          90  Female   Pass

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["Result"] = encoder.fit_transform(df["Result"])#it convert  result class to 0 and 1 ,it can treate 0 to any and 1 to any
df

   Study Hours  Attendance  Gender  Result
0            2          60    Male       0
1            3          65  Female       0
2            4          70    Male       1
3            5          75  Female       1
4            6          80    Male       1
5            7          85  Female       1
6            1          50    Male       0
7            8          90  Female       1

In [9]:
#but if you want to convert manually use map 

df["Result"] = df["Result"].map({"Pass":1,"Fail":0})#convert manually. (a.map() ony words with pandas)
df

   Study Hours  Attendance  Gender  Result
0            2          60    Male     NaN
1            3          65  Female     NaN
2            4          70    Male     NaN
3            5          75  Female     NaN
4            6          80    Male     NaN
5            7          85  Female     NaN
6            1          50    Male     NaN
7            8          90  Female     NaN