In [1]:
import pandas as pd
data = {
    "Name": ['nitan', 'ram', 'hari',"gita"],
    "Age": [28, 28, 22,34],
    "Salary": [30000, 20000, 30000,10000]
}
df=pd.DataFrame(data)

In [2]:
df.sort_values(by=["Age"],ascending=[True],inplace=False)

    Name  Age  Salary
2   hari   22   30000
0  nitan   28   30000
1    ram   28   20000
3   gita   34   10000

In [3]:
df.sort_values(by=["Age","Salary"],ascending=[True,False],inplace=False)

    Name  Age  Salary
2   hari   22   30000
0  nitan   28   30000
1    ram   28   20000
3   gita   34   10000

In [4]:
df.sort_values(by=["Name","Salary"],ascending=[True,False],inplace=False)

    Name  Age  Salary
3   gita   34   10000
2   hari   22   30000
0  nitan   28   30000
1    ram   28   20000