In [14]:
import pandas as pd
data1 = {
    "Name": ['nitan', 'ram', 'hari',"gita"],
    "Age": [28, 34, 22,34],
    "Salary": [10000, 20000, 30000,10000]
}
data2 = {
    "Name": ["ram","hari"],
    "Age": [28, 34],
    "Salary": [10000, 20000]
}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [ ]:
df  = pd.concat([df1,df2],axis=0,ignore_index=True)
#axis=0 means ro2
#axis = 1 means column
df

    Name  Age  Salary
0  nitan   28   10000
1    ram   34   20000
2   hari   22   30000
3   gita   34   10000
4    ram   28   10000
5   hari   34   20000

In [ ]:
# it is not important


data1 = {
    "Name": ['nitan', 'ram', 'hari',"gita"],
    "Age": [28, 34, 22,34],
    
}
data2 = {

    "Salary":[10000,20000,30000,40000]

}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [17]:
df = pd.concat([df1,df2],axis=1)
df

    Name  Age  Salary
0  nitan   28   10000
1    ram   34   20000
2   hari   22   30000
3   gita   34   40000