#Read file

In [23]:
import pandas as pd

In [ ]:
df1=pd.read_csv("data.csv")
df2=pd.read_excel("data.xlsx")#pip instal openpyxl
df3=pd.read_json("data.json")

In [25]:
df1

    Name  Age  salary
0    Ram   28   50000
1  Shyam   29  100000

In [26]:
df2

    Name  Age  salary
0    Ram   28   50000
1  Shyam   29  100000

In [27]:
df3

    Name  Age  salary
0    Ram   28   50000
1  Shyam   29  100000