In [ ]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85.2134, 90.67812, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)

In [12]:
df #it gives all rows

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur

In [13]:
df.head()  #it gives first 5 rows
# df.head(3) #it gives first 3 rows

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur

In [14]:
df.tail()#it gives last 5 rows
# df.tail(3) #it gives last 3 rows

    Name  Age Gender  Math  Science       City
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur