In [40]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85.2134, 90.67812, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)

In [41]:
df

    Name  Age Gender      Math  Science       City
0    Ram   20      M  85.21340       80  Kathmandu
1   Sita   21      F  90.67812       85    Pokhara
2   Hari   19      M  70.00000       75  Kathmandu
3   Gita   22      F  95.00000       90   Lalitpur
4  Nabin   20      M  60.00000       65  Bhaktapur
5   Asha   21      F  88.00000       95    Pokhara
6  Rohan   23      M  75.00000       70  Kathmandu
7   Mina   19      F  92.00000       89   Lalitpur

In [42]:
#gettin columns list 
df.columns

Index(['Name', 'Age', 'Gender', 'Math', 'Science', 'City'], dtype='str')

In [43]:
#indexing and slicing
print(df.columns[0])
print(df.columns[-1])
print(df.columns[2:])
print(df.columns[::-1])

Name
City
Index(['Gender', 'Math', 'Science', 'City'], dtype='str')
Index(['City', 'Science', 'Math', 'Gender', 'Age', 'Name'], dtype='str')

In [ ]:
#getting single column
# df["Name":"Age"] #cant perfrom column slicing

TypeError: cannot do slice indexing on RangeIndex with these indexers [Name] of type str

In [ ]:
#getting multiple columns  
#for multiple columns use []
df[["Name","Age","Gender"]]

    Name  Age Gender
0    Ram   20      M
1   Sita   21      F
2   Hari   19      M
3   Gita   22      F
4  Nabin   20      M
5   Asha   21      F
6  Rohan   23      M
7   Mina   19      F

In [ ]:
df["Name"]

0      Ram
1     Sita
2     Hari
3     Gita
4    Nabin
5     Asha
6    Rohan
7     Mina
Name: Name, dtype: str

In [ ]:
#renaming columns
df.rename(columns={"Name":"First Name"},inplace=True)#inplace =True means change original dataframe
df

  First Name  Age Gender      Math  Science       City
0        Ram   20      M  85.21340       80  Kathmandu
1       Sita   21      F  90.67812       85    Pokhara
2       Hari   19      M  70.00000       75  Kathmandu
3       Gita   22      F  95.00000       90   Lalitpur
4      Nabin   20      M  60.00000       65  Bhaktapur
5       Asha   21      F  88.00000       95    Pokhara
6      Rohan   23      M  75.00000       70  Kathmandu
7       Mina   19      F  92.00000       89   Lalitpur

In [ ]:
# df["First Name":"Age"] #not possible #but it is possible in df.loc[row, column]