adding , changing, deleting columns

In [1]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85.2134, 90.67812, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)

In [2]:
#adding English columns at last
df["English"]=[80,85,70,95,60,88,75,92] #add #english column to last
df

    Name  Age Gender      Math  Science       City  English
0    Ram   20      M  85.21340       80  Kathmandu       80
1   Sita   21      F  90.67812       85    Pokhara       85
2   Hari   19      M  70.00000       75  Kathmandu       70
3   Gita   22      F  95.00000       90   Lalitpur       95
4  Nabin   20      M  60.00000       65  Bhaktapur       60
5   Asha   21      F  88.00000       95    Pokhara       88
6  Rohan   23      M  75.00000       70  Kathmandu       75
7   Mina   19      F  92.00000       89   Lalitpur       92

In [3]:
#Nottttttttttttt impppppppppppp
#addin columns using insert method
#here we can control the position of the new column unlinke direct method 
#df.insert(index_position, column_name, values
df.insert(3,"Nepali", [80,85,70,95,60,88,75,92])# 3 is the index

df

    Name  Age Gender  Nepali      Math  Science       City  English
0    Ram   20      M      80  85.21340       80  Kathmandu       80
1   Sita   21      F      85  90.67812       85    Pokhara       85
2   Hari   19      M      70  70.00000       75  Kathmandu       70
3   Gita   22      F      95  95.00000       90   Lalitpur       95
4  Nabin   20      M      60  60.00000       65  Bhaktapur       60
5   Asha   21      F      88  88.00000       95    Pokhara       88
6  Rohan   23      M      75  75.00000       70  Kathmandu       75
7   Mina   19      F      92  92.00000       89   Lalitpur       92

In [4]:
#changing whole column
df["Math"] = df["Math"] + 5
df

    Name  Age Gender  Nepali       Math  Science       City  English
0    Ram   20      M      80   90.21340       80  Kathmandu       80
1   Sita   21      F      85   95.67812       85    Pokhara       85
2   Hari   19      M      70   75.00000       75  Kathmandu       70
3   Gita   22      F      95  100.00000       90   Lalitpur       95
4  Nabin   20      M      60   65.00000       65  Bhaktapur       60
5   Asha   21      F      88   93.00000       95    Pokhara       88
6  Rohan   23      M      75   80.00000       70  Kathmandu       75
7   Mina   19      F      92   97.00000       89   Lalitpur       92

In [5]:
df["Math"]=df["Math"].round(1) #it is imp
df

    Name  Age Gender  Nepali   Math  Science       City  English
0    Ram   20      M      80   90.2       80  Kathmandu       80
1   Sita   21      F      85   95.7       85    Pokhara       85
2   Hari   19      M      70   75.0       75  Kathmandu       70
3   Gita   22      F      95  100.0       90   Lalitpur       95
4  Nabin   20      M      60   65.0       65  Bhaktapur       60
5   Asha   21      F      88   93.0       95    Pokhara       88
6  Rohan   23      M      75   80.0       70  Kathmandu       75
7   Mina   19      F      92   97.0       89   Lalitpur       92

In [6]:
#changing single columne 
df["Math"] = [90,85,70,95,60,88,75,92]
#chaning multiple column 
df[["Name", "Age"]] = [
    ["A", 20],
    ["B", 21],
    ["C", 22],
    ["D", 23],
    ["E", 24],
    ["F", 25],
    ["G", 26],
    ["H", 27]
]
df

  Name Age Gender  Nepali  Math  Science       City  English
0    A  20      M      80    90       80  Kathmandu       80
1    B  21      F      85    85       85    Pokhara       85
2    C  22      M      70    70       75  Kathmandu       70
3    D  23      F      95    95       90   Lalitpur       95
4    E  24      M      60    60       65  Bhaktapur       60
5    F  25      F      88    88       95    Pokhara       88
6    G  26      M      75    75       70  Kathmandu       75
7    H  27      F      92    92       89   Lalitpur       92

In [7]:
#drop
#df.drop(columns=["Name","Age"], inplace=True) 
#inplce=True means change the original dataframe if it is false it will not change the original dataframe rather it will create a new dataframe
# df.drop(columns=["Name","Age"], inplace=True)
df

  Name Age Gender  Nepali  Math  Science       City  English
0    A  20      M      80    90       80  Kathmandu       80
1    B  21      F      85    85       85    Pokhara       85
2    C  22      M      70    70       75  Kathmandu       70
3    D  23      F      95    95       90   Lalitpur       95
4    E  24      M      60    60       65  Bhaktapur       60
5    F  25      F      88    88       95    Pokhara       88
6    G  26      M      75    75       70  Kathmandu       75
7    H  27      F      92    92       89   Lalitpur       92

In [8]:
# df["Math"][0]=9# it does not works
#changin specfic column value 
# df