.loc[] is used to  get

row  by index 

column by Name


df.loc[row_index]

df.loc[row_index, column_name]

for single row_index use 1 

for multiple row_index  use [1,2]

for single column_name use "column_name"

for multiple column_name use ["column_name1","column_name2"]

In [20]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85, 90, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)
df

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur

In [21]:

# df.loc[row_index, column_name]=new_value
#for single row_indes use 1 
#for multiple row_index  use [1,2]
#for single column_name use "column_name"
#for multiple column_name use ["column_name1","column_name2"]

In [22]:
#selectin a row by index level
print(df.loc[0])

Name             Ram
Age               20
Gender             M
Math              85
Science           80
City       Kathmandu
Name: 0, dtype: object

In [23]:
#selecting a multiple rows by index level
print(df.loc[[0,1,2,3]])

   Name  Age Gender  Math  Science       City
0   Ram   20      M    85       80  Kathmandu
1  Sita   21      F    90       85    Pokhara
2  Hari   19      M    70       75  Kathmandu
3  Gita   22      F    95       90   Lalitpur

In [24]:
#selectin a multiple rows using slicing
print(df.loc[:3])#it include end index as well

   Name  Age Gender  Math  Science       City
0   Ram   20      M    85       80  Kathmandu
1  Sita   21      F    90       85    Pokhara
2  Hari   19      M    70       75  Kathmandu
3  Gita   22      F    95       90   Lalitpur

In [25]:
#selectin row and column
df.loc[[0,1],"Math"]#select 0 and 1 row and give Math column

0    85
1    90
Name: Math, dtype: int64

In [26]:
df.loc[[0,1],["Math","Science"]]#show  0 and 1 row and show Math and Science column

   Math  Science
0    85       80
1    90       85

In [27]:
df.loc[:,["Math","Science"]]#show all row and show Math and Science column

   Math  Science
0    85       80
1    90       85
2    70       75
3    95       90
4    60       65
5    88       95
6    75       70
7    92       89

In [28]:
df

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur

In [29]:
df.loc[:,"Name":"Math"]#show all row and show Name to Math
#it include Math as well

    Name  Age Gender  Math
0    Ram   20      M    85
1   Sita   21      F    90
2   Hari   19      M    70
3   Gita   22      F    95
4  Nabin   20      M    60
5   Asha   21      F    88
6  Rohan   23      M    75
7   Mina   19      F    92

    Name  Age Gender  Math  Science
0    Ram   20      M    90       80
1   Sita   21      F    90       85
2   Hari   19      M    70       75
3   Gita   22      F    95       90
4  Nabin   20      M    60       65
5   Asha   21      F    88       95
6  Rohan   23      M    75       70
7   Mina   19      F    92       89

In [31]:

print(df["Math"][0])#we can get specific cell
df["Math"][0]=90  #it can not update specific cell
df

85

C:\Users\acer\AppData\Local\Temp\ipykernel_13584\843388055.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["Math"][0]=90  #it can not update specific cell

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur

In [32]:
print(df.loc[0,"Math"])#we can get specific cell
df.loc[0,"Math"]=90  #it can  update specific cell
df

85

    Name  Age Gender  Math  Science       City
0    Ram   20      M    90       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur