##filter row by column condition

In [2]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Math": [85, 90, 70, 95, 60, 88, 75, 92],
    "Science": [80, 85, 75, 90, 65, 95, 70, 89],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur",
             "Bhaktapur", "Pokhara", "Kathmandu", "Lalitpur"]
}

df = pd.DataFrame(data)
df

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
1   Sita   21      F    90       85    Pokhara
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
5   Asha   21      F    88       95    Pokhara
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur

In [3]:
df[df["City"] == "Pokhara"]

   Name  Age Gender  Math  Science     City
1  Sita   21      F    90       85  Pokhara
5  Asha   21      F    88       95  Pokhara

In [4]:
df[(df["Math"] > 80) & (df["Science"] > 80)]  #must give ()

   Name  Age Gender  Math  Science      City
1  Sita   21      F    90       85   Pokhara
3  Gita   22      F    95       90  Lalitpur
5  Asha   21      F    88       95   Pokhara
7  Mina   19      F    92       89  Lalitpur

In [5]:
df[(df["City"] == "Pokhara")|(df["City"] == "Lalitpur"  )]

   Name  Age Gender  Math  Science      City
1  Sita   21      F    90       85   Pokhara
3  Gita   22      F    95       90  Lalitpur
5  Asha   21      F    88       95   Pokhara
7  Mina   19      F    92       89  Lalitpur

In [6]:
df[~(df["City"]=="Pokhara")]

    Name  Age Gender  Math  Science       City
0    Ram   20      M    85       80  Kathmandu
2   Hari   19      M    70       75  Kathmandu
3   Gita   22      F    95       90   Lalitpur
4  Nabin   20      M    60       65  Bhaktapur
6  Rohan   23      M    75       70  Kathmandu
7   Mina   19      F    92       89   Lalitpur

In [7]:
#using loc
df.loc[df["Math"]>80]  #ge

   Name  Age Gender  Math  Science       City
0   Ram   20      M    85       80  Kathmandu
1  Sita   21      F    90       85    Pokhara
3  Gita   22      F    95       90   Lalitpur
5  Asha   21      F    88       95    Pokhara
7  Mina   19      F    92       89   Lalitpur

In [8]:
df.loc[:,df.columns != "City"]  #you can select columns using filter condition

    Name  Age Gender  Math  Science
0    Ram   20      M    85       80
1   Sita   21      F    90       85
2   Hari   19      M    70       75
3   Gita   22      F    95       90
4  Nabin   20      M    60       65
5   Asha   21      F    88       95
6  Rohan   23      M    75       70
7   Mina   19      F    92       89