In [301]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Ram", "Sita", "Hari", "Gita", "Nabin", "Asha", "Rohan", "Mina", "Bikash", "Anita"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19, np.nan, 22],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur", "Kathmandu",
             "Pokhara", "Lalitpur", "Kathmandu", "Pokhara", "Kathmandu"],
    "Math": [80, 95, 75, np.nan, 85, 95, 60, 70, 88, 92],
    "Science": [75, 85, 80, 90, np.nan, 88, 65, 72, 82, 95],
    "English": [85, 88, 78, 92, 80, np.nan, 70, 75, 85, 90],
    "Attendance": [90, np.nan, 85, 92, np.nan, 98, np.nan, 80, np.nan, 96],
    "Grade": ["B", "A", "B", "A", "B", "A", "C", "C", "B", "A"]
}

df = pd.DataFrame(data)

In [302]:
df

     Name   Age Gender       City  Math  Science  English  Attendance Grade
0     Ram  20.0      M  Kathmandu  80.0     75.0     85.0        90.0     B
1    Sita  21.0      F    Pokhara  95.0     85.0     88.0         NaN     A
2    Hari  19.0      M  Kathmandu  75.0     80.0     78.0        85.0     B
3    Gita  22.0      F   Lalitpur   NaN     90.0     92.0        92.0     A
4   Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN     B
5    Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A
6   Rohan  23.0      M   Lalitpur  60.0     65.0     70.0         NaN     C
7    Mina  19.0      F  Kathmandu  70.0     72.0     75.0        80.0     C
8  Bikash   NaN      M    Pokhara  88.0     82.0     85.0         NaN     B
9   Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0     A

find the number of rows and columns

display all columns names 

check data types of all columns

find the mean ,median,mode,of math marks

select 2, 5 rows using loc

select 2, 5 rows uing iloc

select all rows and Math, Science and English column usie loc

select all rows and Math, Science and English column usie iloc

select grade in Y  and all in X

find studetn whose Math marks are greater than 80

find student whose grade is A

find student who are female and from kathmandu

find studetns who score more than 80 in all math, science and english

Find students who scored above the average Math mark.

find the students(row) who got heighest and smallest  marks in Math

find the  top 5 student who got heighest marks in Math

find the  4 number student who got heighest marks in Math use iloc

find the 4 number studets name who got heightes marks in Math

find how many missing value each column has

find the total number of missing values 

fill missing age with mean 

removing rows containg missing value 

remove columns containing missing values

remove columns that have less than 80% non-null data

find total number of males, female

find the most common grade

# create average column from  math, scienc, english 
#create result if  average>=80 then distinction  if average>=60 then first else pass

change M value by Male , F to Female

In [303]:
#find the number of rows and columns
df.shape

(10, 9)

In [304]:
#display all columns names 
df.columns

Index(['Name', 'Age', 'Gender', 'City', 'Math', 'Science', 'English',
       'Attendance', 'Grade'],
      dtype='str')

In [305]:
#check data types of all columns 
# df.info()
df.dtypes

Name              str
Age           float64
Gender            str
City              str
Math          float64
Science       float64
English       float64
Attendance    float64
Grade             str
dtype: object

In [306]:
#find the students(row) who got heighest and smallest  marks in Math
df[df["Math"]==df["Math"].max()]

   Name   Age Gender     City  Math  Science  English  Attendance Grade
1  Sita  21.0      F  Pokhara  95.0     85.0     88.0         NaN     A
5  Asha  21.0      F  Pokhara  95.0     88.0      NaN        98.0     A

In [307]:
##find the students(row) who got heighest and smallest  marks in Math
df[df["Math"]==df["Math"].min()]

    Name   Age Gender      City  Math  Science  English  Attendance Grade
6  Rohan  23.0      M  Lalitpur  60.0     65.0     70.0         NaN     C

In [308]:
#find the mean of math marks 
print(df['Math'].mean())#nan is not considered when calculating the median by default.
print(df["Math"].median())#nan is not considered when calculating the median by default.
print(df["Math"].mode())#nan is not considered when calculating the median by default.

82.22222222222223
85.0
0    95.0
Name: Math, dtype: float64

In [309]:
#select 2, 5 rows using loc
df.loc[2:5]

    Name   Age Gender       City  Math  Science  English  Attendance Grade
2   Hari  19.0      M  Kathmandu  75.0     80.0     78.0        85.0     B
3   Gita  22.0      F   Lalitpur   NaN     90.0     92.0        92.0     A
4  Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN     B
5   Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A

In [310]:
#select 2, 5 rows using iloc
df.iloc[2:6]

    Name   Age Gender       City  Math  Science  English  Attendance Grade
2   Hari  19.0      M  Kathmandu  75.0     80.0     78.0        85.0     B
3   Gita  22.0      F   Lalitpur   NaN     90.0     92.0        92.0     A
4  Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN     B
5   Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A

In [311]:
#select all rows and Math, Science and English column
# df[["Math", "Science", "English"]]#or
df.loc[:,["Math", "Science", "English"]]

   Math  Science  English
0  80.0     75.0     85.0
1  95.0     85.0     88.0
2  75.0     80.0     78.0
3   NaN     90.0     92.0
4  85.0      NaN     80.0
5  95.0     88.0      NaN
6  60.0     65.0     70.0
7  70.0     72.0     75.0
8  88.0     82.0     85.0
9  92.0     95.0     90.0

In [312]:
#select grade in Y  and all in X
y = df["Grade"]
print(y)
# x= df.drop(columns = ["Grade"])
x=df.loc[:,df.columns != "Grade"]
print(x)

0    B
1    A
2    B
3    A
4    B
5    A
6    C
7    C
8    B
9    A
Name: Grade, dtype: str
     Name   Age Gender       City  Math  Science  English  Attendance
0     Ram  20.0      M  Kathmandu  80.0     75.0     85.0        90.0
1    Sita  21.0      F    Pokhara  95.0     85.0     88.0         NaN
2    Hari  19.0      M  Kathmandu  75.0     80.0     78.0        85.0
3    Gita  22.0      F   Lalitpur   NaN     90.0     92.0        92.0
4   Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN
5    Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0
6   Rohan  23.0      M   Lalitpur  60.0     65.0     70.0         NaN
7    Mina  19.0      F  Kathmandu  70.0     72.0     75.0        80.0
8  Bikash   NaN      M    Pokhara  88.0     82.0     85.0         NaN
9   Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0

In [313]:
# find studetn whose Math marks are greater than 80
df[df["Math"]>80]

     Name   Age Gender       City  Math  Science  English  Attendance Grade
1    Sita  21.0      F    Pokhara  95.0     85.0     88.0         NaN     A
4   Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN     B
5    Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A
8  Bikash   NaN      M    Pokhara  88.0     82.0     85.0         NaN     B
9   Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0     A

In [314]:
#find student whose grade is A
df[df["Grade"] == "A"]

    Name   Age Gender       City  Math  Science  English  Attendance Grade
1   Sita  21.0      F    Pokhara  95.0     85.0     88.0         NaN     A
3   Gita  22.0      F   Lalitpur   NaN     90.0     92.0        92.0     A
5   Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A
9  Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0     A

In [315]:
#find student who are female and from kathmandu
df[(df["Gender"]=="F") &(df["City"]=="Kathmandu")]

    Name   Age Gender       City  Math  Science  English  Attendance Grade
7   Mina  19.0      F  Kathmandu  70.0     72.0     75.0        80.0     C
9  Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0     A

In [332]:
#find studetns who score more than 80 in all math, science and english
df[(df["Math"]>80) & (df["Science"]>80) & (df["English"]>80)]

,Name,Age,Gender,City,Math,Science,English,Attendance,Grade,Average,Result
1,Sita,21.0,Female,Pokhara,95.000000,85.0,88.000000,NaN,A,89.333333,Distinction
3,Gita,22.0,Female,Lalitpur,82.222222,90.0,92.000000,92.0,A,88.074074,Distinction
5,Asha,21.0,Female,Pokhara,95.000000,88.0,82.555556,98.0,A,88.518519,Distinction
8,Bikash,NaN,Male,Pokhara,88.000000,82.0,85.000000,NaN,B,85.000000,Distinction
9,Anita,22.0,Female,Kathmandu,92.000000,95.0,90.000000,96.0,A,92.333333,Distinction

In [333]:
#find students who score above the average Math marks 
df[df["Math"]>=df["Math"].mean()]

,Name,Age,Gender,City,Math,Science,English,Attendance,Grade,Average,Result
1,Sita,21.0,Female,Pokhara,95.000000,85.000000,88.000000,NaN,A,89.333333,Distinction
3,Gita,22.0,Female,Lalitpur,82.222222,90.000000,92.000000,92.0,A,88.074074,Distinction
4,Nabin,20.0,Male,Kathmandu,85.000000,81.333333,80.000000,NaN,B,82.111111,Distinction
5,Asha,21.0,Female,Pokhara,95.000000,88.000000,82.555556,98.0,A,88.518519,Distinction
8,Bikash,NaN,Male,Pokhara,88.000000,82.000000,85.000000,NaN,B,85.000000,Distinction
9,Anita,22.0,Female,Kathmandu,92.000000,95.000000,90.000000,96.0,A,92.333333,Distinction

In [317]:
#find the  top 5 shudent who got heighest marks in Math
df.sort_values(by=["Math"],ascending=[False]).head(5)

     Name   Age Gender       City  Math  Science  English  Attendance Grade
1    Sita  21.0      F    Pokhara  95.0     85.0     88.0         NaN     A
5    Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A
9   Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0     A
8  Bikash   NaN      M    Pokhara  88.0     82.0     85.0         NaN     B
4   Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN     B

In [318]:
#find the  4 student who got heighest marks in Math
# df.sort_values(by=["Math"],ascending=[False]).head().loc[3]   #this gives error because 3 index is missing 
df.sort_values(by=["Math"],ascending=[False]).head(4).iloc[3]  #this is the correct way, iloc itself assign index from 0, 1,2,3

Name           Bikash
Age               NaN
Gender              M
City          Pokhara
Math             88.0
Science          82.0
English          85.0
Attendance        NaN
Grade               B
Name: 8, dtype: object

In [319]:
#find the 4 number studets name who got heightes marks in Math
d1 =df.sort_values(by=["Math"],ascending=[False]).head(4).iloc[3]
d1["Name"]

'Bikash'

In [320]:
# find how many missing value each column has
df.isna().sum()

Name          0
Age           1
Gender        0
City          0
Math          1
Science       1
English       1
Attendance    4
Grade         0
dtype: int64

In [321]:
# find the total number of missing values 
df.isna().sum().sum()

np.int64(8)

In [ ]:
# # find the rows contaiing at least one missing value 
# df[df.isnull().any(axis=1)]

     Name   Age Gender       City  Math  Science  English  Attendance Grade
1    Sita  21.0      F    Pokhara  95.0     85.0     88.0         NaN     A
3    Gita  22.0      F   Lalitpur   NaN     90.0     92.0        92.0     A
4   Nabin  20.0      M  Kathmandu  85.0      NaN     80.0         NaN     B
5    Asha  21.0      F    Pokhara  95.0     88.0      NaN        98.0     A
6   Rohan  23.0      M   Lalitpur  60.0     65.0     70.0         NaN     C
8  Bikash   NaN      M    Pokhara  88.0     82.0     85.0         NaN     B

In [323]:
# fill missing age with mean 
df.fillna({"Age":df["Age"].mean()})

,Name,Age,Gender,City,Math,Science,English,Attendance,Grade
0,Ram,20.000000,M,Kathmandu,80.0,75.0,85.0,90.0,B
1,Sita,21.000000,F,Pokhara,95.0,85.0,88.0,NaN,A
2,Hari,19.000000,M,Kathmandu,75.0,80.0,78.0,85.0,B
3,Gita,22.000000,F,Lalitpur,NaN,90.0,92.0,92.0,A
4,Nabin,20.000000,M,Kathmandu,85.0,NaN,80.0,NaN,B
5,Asha,21.000000,F,Pokhara,95.0,88.0,NaN,98.0,A
6,Rohan,23.000000,M,Lalitpur,60.0,65.0,70.0,NaN,C
7,Mina,19.000000,F,Kathmandu,70.0,72.0,75.0,80.0,C
8,Bikash,20.777778,M,Pokhara,88.0,82.0,85.0,NaN,B
9,Anita,22.000000,F,Kathmandu,92.0,95.0,90.0,96.0,A

In [324]:
# removing rows containg missing value 
df.dropna(axis=0)

    Name   Age Gender       City  Math  Science  English  Attendance Grade
0    Ram  20.0      M  Kathmandu  80.0     75.0     85.0        90.0     B
2   Hari  19.0      M  Kathmandu  75.0     80.0     78.0        85.0     B
7   Mina  19.0      F  Kathmandu  70.0     72.0     75.0        80.0     C
9  Anita  22.0      F  Kathmandu  92.0     95.0     90.0        96.0     A

In [325]:
# removing columns containg missing value
df.dropna(axis=1)

     Name Gender       City Grade
0     Ram      M  Kathmandu     B
1    Sita      F    Pokhara     A
2    Hari      M  Kathmandu     B
3    Gita      F   Lalitpur     A
4   Nabin      M  Kathmandu     B
5    Asha      F    Pokhara     A
6   Rohan      M   Lalitpur     C
7    Mina      F  Kathmandu     C
8  Bikash      M    Pokhara     B
9   Anita      F  Kathmandu     A

In [326]:
# df.shape[0]#or
len(df)

10

In [327]:
# remove columns that have less than 80% non-null data
df.dropna(axis=1, thresh=int(df.shape[0]*0.8))#it remove attandance column

     Name   Age Gender       City  Math  Science  English Grade
0     Ram  20.0      M  Kathmandu  80.0     75.0     85.0     B
1    Sita  21.0      F    Pokhara  95.0     85.0     88.0     A
2    Hari  19.0      M  Kathmandu  75.0     80.0     78.0     B
3    Gita  22.0      F   Lalitpur   NaN     90.0     92.0     A
4   Nabin  20.0      M  Kathmandu  85.0      NaN     80.0     B
5    Asha  21.0      F    Pokhara  95.0     88.0      NaN     A
6   Rohan  23.0      M   Lalitpur  60.0     65.0     70.0     C
7    Mina  19.0      F  Kathmandu  70.0     72.0     75.0     C
8  Bikash   NaN      M    Pokhara  88.0     82.0     85.0     B
9   Anita  22.0      F  Kathmandu  92.0     95.0     90.0     A

In [328]:
# find total number of males, femaisl ...

df.value_counts("Gender")

Gender
M    5
F    5
Name: count, dtype: int64

In [329]:
#find the most common grade
df.value_counts("Grade").index[0]

'B'

In [330]:
# create average column of  math, scienc, english 
#create result if  marks>=80 then distinction  if marks>=60 then first else pass
# df["Average"] = (df["Math"]+df["Science"]+df["English"])/3
# df

#whye NaN +1 = NaN thus before averagint you need to replace NaN value 

df.fillna({
    "Math":df["Math"].mean(),
    "Science":df["Science"].mean(),
    "English":df["English"].mean()
    },inplace=True)
df
df["Average"] = (df["Math"]+df["Science"]+df["English"])/3  
df["Result"] = [ "Distinction" if el>=80 else "First" if el>=60 else "Pass" for el in df["Average"]]
df

,Name,Age,Gender,City,Math,Science,English,Attendance,Grade,Average,Result
0,Ram,20.0,M,Kathmandu,80.000000,75.000000,85.000000,90.0,B,80.000000,Distinction
1,Sita,21.0,F,Pokhara,95.000000,85.000000,88.000000,NaN,A,89.333333,Distinction
2,Hari,19.0,M,Kathmandu,75.000000,80.000000,78.000000,85.0,B,77.666667,First
3,Gita,22.0,F,Lalitpur,82.222222,90.000000,92.000000,92.0,A,88.074074,Distinction
4,Nabin,20.0,M,Kathmandu,85.000000,81.333333,80.000000,NaN,B,82.111111,Distinction
5,Asha,21.0,F,Pokhara,95.000000,88.000000,82.555556,98.0,A,88.518519,Distinction
6,Rohan,23.0,M,Lalitpur,60.000000,65.000000,70.000000,NaN,C,65.000000,First
7,Mina,19.0,F,Kathmandu,70.000000,72.000000,75.000000,80.0,C,72.333333,First
8,Bikash,NaN,M,Pokhara,88.000000,82.000000,85.000000,NaN,B,85.000000,Distinction
9,Anita,22.0,F,Kathmandu,92.000000,95.000000,90.000000,96.0,A,92.333333,Distinction

In [331]:
#change M value by Male , F to Female

# df["Gender"] =  [ "Male" if el=="M" else "Female" for el in df["Gender"]]
# df

#or 
df["Gender"] = df["Gender"].apply(lambda el: "Male" if el=="M" else "Female")
df

,Name,Age,Gender,City,Math,Science,English,Attendance,Grade,Average,Result
0,Ram,20.0,Male,Kathmandu,80.000000,75.000000,85.000000,90.0,B,80.000000,Distinction
1,Sita,21.0,Female,Pokhara,95.000000,85.000000,88.000000,NaN,A,89.333333,Distinction
2,Hari,19.0,Male,Kathmandu,75.000000,80.000000,78.000000,85.0,B,77.666667,First
3,Gita,22.0,Female,Lalitpur,82.222222,90.000000,92.000000,92.0,A,88.074074,Distinction
4,Nabin,20.0,Male,Kathmandu,85.000000,81.333333,80.000000,NaN,B,82.111111,Distinction
5,Asha,21.0,Female,Pokhara,95.000000,88.000000,82.555556,98.0,A,88.518519,Distinction
6,Rohan,23.0,Male,Lalitpur,60.000000,65.000000,70.000000,NaN,C,65.000000,First
7,Mina,19.0,Female,Kathmandu,70.000000,72.000000,75.000000,80.0,C,72.333333,First
8,Bikash,NaN,Male,Pokhara,88.000000,82.000000,85.000000,NaN,B,85.000000,Distinction
9,Anita,22.0,Female,Kathmandu,92.000000,95.000000,90.000000,96.0,A,92.333333,Distinction